# Generated by Django 4.1.7 on 2023-03-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_alter_demandercritiquemod_img_livre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandercritiquemod',
            name='img_livre',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
