# Generated by Django 4.1.7 on 2023-03-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemanderCritiqueMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1025)),
                ('img_livre', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CreerCritiqueMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('note', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=3)),
                ('commentaire', models.CharField(max_length=600)),
                ('demande_de_critique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.demandercritiquemod')),
            ],
        ),
    ]
