# Generated by Django 4.1.7 on 2023-03-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creercritiquemod',
            name='demande_de_critique',
        ),
        migrations.AddField(
            model_name='demandercritiquemod',
            name='reponse_critique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.creercritiquemod'),
        ),
    ]
