# Generated by Django 4.1.7 on 2023-03-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandercritiquemod',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandercritiquemod',
            name='reponse_critique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.creercritiquemod'),
        ),
        migrations.AddField(
            model_name='creercritiquemod',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
