# Generated by Django 4.1.7 on 2023-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_remove_creercritiquemod_demande_de_critique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creercritiquemod',
            name='createur',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandercritiquemod',
            name='createur',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
